version: "3.3"

services:
  postgres:
    image: postgres:15.1
    ports:
    - "127.0.0.1:7887:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yeahwecan
    volumes:
    - $HOME/docker/volumes/tabdil/postgres:/var/lib/postgresql/data
